-- Create use_cases table
CREATE TABLE IF NOT EXISTS use_cases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  detailed_description TEXT,
  industry TEXT NOT NULL,
  department TEXT NOT NULL,
  tools TEXT[],
  time_saved TEXT,
  complexity TEXT,
  icon TEXT,
  accent_color TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  published BOOLEAN DEFAULT TRUE
);

-- Enable Row Level Security
ALTER TABLE use_cases ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Public read access" ON use_cases
  FOR SELECT USING (published = true);

-- Seed data with 25+ realistic use cases
INSERT INTO use_cases (title, description, detailed_description, industry, department, tools, time_saved, complexity, icon, accent_color) VALUES

-- Financial Services
('Automated Compliance Report Generation', 'An OpenClaw agent compiles regulatory reports from transaction data, risk assessments, and audit logs.', 'An OpenClaw agent gathers data from multiple systems, apply compliance frameworks, generate formatted reports, and route for approval. Reduces manual data gathering and formatting time by 80%. The agent uses OpenClaw's built-in integrations (Slack, email, browser, database access) to monitor triggers, process data, and execute workflows end-to-end.', 'Financial Services', 'Operations', ARRAY['OpenClaw', 'Slack', 'Database', 'Compliance Tools'], '8-12 hrs/week', 'Moderate', 'clipboard', 'a'),

('Fraud Detection Alert Routing', 'An OpenClaw agent provides real-time analysis of transaction patterns with automated escalation to risk teams.', 'An OpenClaw agent monitors transaction streams, apply ML models for anomaly detection, create structured alerts with context, and route to appropriate team members based on severity and type.', 'Financial Services', 'Operations', ARRAY['OpenClaw', 'Database', 'Slack', 'Risk System'], '5-8 hrs/week', 'Advanced', 'shield', 'c'),

('Client Onboarding Automation', 'An OpenClaw agent streamlines KYC document collection, verification, and account setup workflows.', 'An OpenClaw agent provides automated document request emails, OCR extraction of ID documents, verification checks, CRM updates, and account provisioning triggers. Reduces onboarding time from days to hours. The agent uses OpenClaw's built-in integrations to orchestrate the full workflow across systems.', 'Financial Services', 'Sales', ARRAY['OpenClaw', 'Email', 'DocuSign', 'CRM', 'Database'], '10-15 hrs/week', 'Moderate', 'rocket', 'b'),

-- Healthcare
('Patient Intake Form Processing', 'An OpenClaw agent extracts structured data from intake forms and route to appropriate care teams.', 'An OpenClaw agent uses OCR to and NLP extraction of patient information, medical history, insurance details. Auto-populate EHR systems, flag urgent cases, and assign to care coordinators based on condition and specialty.', 'Healthcare', 'Operations', ARRAY['OpenClaw', 'Email', 'EHR', 'Slack'], '12-18 hrs/week', 'Moderate', 'clipboard', 'a'),

('Appointment Reminder Automation', 'An OpenClaw agent sends personalized appointment reminders via SMS/email with rescheduling links.', 'An OpenClaw agent pulls upcoming appointments from scheduling system, generate personalized messages with location, preparation instructions, and one-click reschedule links. Track confirmations and send to no-show risk list. OpenClaw monitors your scheduling system and handles outreach automatically.', 'Healthcare', 'Operations', ARRAY['OpenClaw', 'Scheduling System', 'Twilio', 'Email'], '6-10 hrs/week', 'Simple', 'calendar', 'c'),

('Clinical Trial Eligibility Screening', 'An OpenClaw agent matches patient profiles against trial criteria and generate referral recommendations.', 'An OpenClaw agent analyzes patient records against inclusion/exclusion criteria for active trials, calculate eligibility scores, generate referral packets with supporting evidence, and notify research coordinators. OpenClaw orchestrates data extraction, matching, and notification across your systems.', 'Healthcare', 'Operations', ARRAY['OpenClaw', 'EHR', 'Database', 'Email'], '8-12 hrs/week', 'Advanced', 'chart', 'b'),

-- Legal
('Contract Review and Clause Extraction', 'An OpenClaw agent analyzes contracts to extract key terms, obligations, and flag non-standard clauses.', 'An OpenClaw agent processes uploaded contracts, apply NLP to identify key sections (payment terms, liabilities, IP rights), extract into structured data, highlight deviations from standard templates, and generate review summaries. OpenClaw handles document analysis and reporting end-to-end using its AI and integration capabilities.', 'Legal', 'Legal', ARRAY['OpenClaw', 'Document Management', 'Database', 'Slack'], '15-20 hrs/week', 'Advanced', 'document', 'a'),

('Legal Research Summarization', 'An OpenClaw agent provides automated case law research with summarized findings and citation extraction.', 'An OpenClaw agent queries legal databases, retrieve relevant cases and statutes, generate summaries with key holdings and citations, organize by relevance and jurisdiction, and export to case management system. OpenClaw queries legal databases and formats results automatically.', 'Legal', 'Legal', ARRAY['OpenClaw', 'LexisNexis', 'Notion', 'Email'], '10-15 hrs/week', 'Advanced', 'search', 'c'),

('Matter Intake and Conflict Checking', 'An OpenClaw agent streamlines new matter intake with automated conflict checks and case setup.', 'An OpenClaw agent collects client information via form, run conflict checks against existing matters and relationships, create case folders, assign case numbers, and notify assigned attorneys with intake summary. OpenClaw orchestrates intake, conflict checking, and case setup across your systems.', 'Legal', 'Operations', ARRAY['OpenClaw', 'CRM', 'Database', 'Slack'], '5-8 hrs/week', 'Moderate', 'shield', 'b'),

-- Retail
('Customer Review Sentiment Analysis', 'An OpenClaw agent analyzes product reviews, categorize sentiment, and generate response drafts.', 'An OpenClaw agent monitors reviews across platforms, apply sentiment analysis, categorize by product/issue type, flag urgent negative reviews, generate personalized response drafts, and route to customer service for approval.', 'Retail', 'Marketing', ARRAY['OpenClaw', 'Review Platforms', 'Slack', 'CRM'], '8-12 hrs/week', 'Moderate', 'star', 'a'),

('Inventory Restock Forecasting', 'An OpenClaw agent predicts inventory needs based on sales trends, seasonality, and promotions.', 'An OpenClaw agent analyzes historical sales data, factor in upcoming promotions and seasonal trends, calculate reorder points, generate purchase orders, and alert procurement team when stock levels trigger reorder thresholds.', 'Retail', 'Operations', ARRAY['OpenClaw', 'Inventory System', 'Database', 'Email'], '6-10 hrs/week', 'Advanced', 'chart', 'c'),

('Personalized Marketing Campaign Generation', 'An OpenClaw agent creates segmented email campaigns based on customer behavior and preferences.', 'An OpenClaw agent segments customers by purchase history and browsing behavior, generate personalized product recommendations, create email copy variations, schedule sends at optimal times, and track engagement metrics. OpenClaw creates, segments, and sends campaigns using email and CRM integrations.', 'Retail', 'Marketing', ARRAY['Email Platform', 'CRM', 'Analytics'], '10-15 hrs/week', 'Moderate', 'target', 'b'),

-- Manufacturing
('Quality Assurance Report Automation', 'Aggregate QA data, identify trends, and generate compliance reports.', 'An OpenClaw agent collects inspection data from production lines, calculate defect rates and trends, identify problematic batches or machines, generate formatted reports, and alert quality managers to threshold breaches. OpenClaw monitors production data and generates compliance reports automatically.', 'Manufacturing', 'Operations', ARRAY['OpenClaw', 'Database', 'Slack', 'Reporting Tools'], '8-12 hrs/week', 'Moderate', 'clipboard', 'a'),

('Predictive Maintenance Scheduling', 'An OpenClaw agent analyzes equipment sensor data to predict failures and schedule maintenance.', 'An OpenClaw agent monitors equipment telemetry, apply predictive models to identify failure risk, generate maintenance work orders, schedule downtime to minimize production impact, and notify maintenance teams with parts lists. OpenClaw analyzes sensor data and schedules maintenance using its CMMS and messaging integrations.', 'Manufacturing', 'Operations', ARRAY['OpenClaw', 'IoT Platform', 'CMMS', 'Slack'], '12-18 hrs/week', 'Advanced', 'wrench', 'c'),

('Supply Chain Exception Management', 'An OpenClaw agent monitors supplier delays and automatically trigger contingency workflows.', 'An OpenClaw agent tracks shipments and supplier performance, detect delays or quality issues, calculate production impact, trigger backup supplier orders or production schedule adjustments, and notify planning team. OpenClaw tracks supply chain status and triggers contingency workflows across ERP and messaging tools.', 'Manufacturing', 'Operations', ARRAY['OpenClaw', 'ERP', 'Email', 'Slack'], '10-15 hrs/week', 'Advanced', 'link', 'b'),

-- Technology
('Automated Code Review Summaries', 'An OpenClaw agent reviews pull requests, identifies patterns, and generates review comments.', 'An OpenClaw agent scans PR diffs, check for style violations, security issues, and test coverage, suggest improvements, generate summary for human reviewers, and post to GitHub/GitLab with inline comments. OpenClaw reviews code changes and posts feedback using GitHub integrations.', 'Technology', 'Engineering', ARRAY['OpenClaw', 'GitHub', 'Slack', 'CI/CD'], '10-15 hrs/week', 'Advanced', 'code', 'a'),

('Incident Response Triage', 'Automatically categorize, prioritize, and route production incidents.', 'An OpenClaw agent monitors alerting systems, extract incident details, classify by severity and affected systems, assign to on-call engineers, create incident channels, and post runbooks and recent changes for context. OpenClaw classifies incidents and routes them to on-call engineers with relevant context.', 'Technology', 'Engineering', ARRAY['OpenClaw', 'PagerDuty', 'Slack', 'Jira'], '8-12 hrs/week', 'Moderate', 'alert', 'c'),

('Product Analytics Digest', 'Weekly summary of key product metrics with insights and anomaly alerts.', 'An OpenClaw agent queries analytics platform for core KPIs, identify significant changes or trends, generate visualizations, summarize in plain language, and distribute to product team via Slack and email. OpenClaw generates analytics summaries and distributes them automatically.', 'Technology', 'Executive', ARRAY['OpenClaw', 'Analytics', 'Slack', 'Email'], '5-8 hrs/week', 'Moderate', 'chart', 'b'),

('Customer Support Ticket Classification', 'Auto-tag and route support tickets based on issue type and urgency.', 'An OpenClaw agent parses incoming tickets, extract issue type and sentiment, assign priority score, route to specialized queues, suggest knowledge base articles, and generate draft responses for common issues. OpenClaw classifies tickets and routes them using Zendesk and Slack integrations.', 'Technology', 'Customer Support', ARRAY['OpenClaw', 'Zendesk', 'Slack', 'Knowledge Base'], '12-18 hrs/week', 'Moderate', 'ticket', 'a'),

-- Education
('Student Assignment Grading Assistant', 'An OpenClaw agent provides automated grading of short-answer questions with feedback generation.', 'An OpenClaw agent analyzes student submissions against rubrics, assign preliminary scores, generate personalized feedback highlighting strengths and areas for improvement, flag edge cases for instructor review. OpenClaw grades assignments and generates feedback using LMS integrations.', 'Education', 'Operations', ARRAY['OpenClaw', 'LMS', 'Email', 'Database'], '15-25 hrs/week', 'Advanced', 'clipboard', 'c'),

('Course Recommendation Engine', 'An OpenClaw agent suggests personalized course paths based on student goals and performance.', 'An OpenClaw agent analyzes student transcripts, career goals, and learning patterns, match against course catalog and prerequisites, generate recommended learning paths, and send personalized emails with enrollment links. OpenClaw analyzes transcripts and recommends courses automatically.', 'Education', 'Operations', ARRAY['OpenClaw', 'LMS', 'Email', 'CRM'], '6-10 hrs/week', 'Moderate', 'target', 'b'),

('Alumni Engagement Automation', 'An OpenClaw agent tracks alumni milestones and trigger personalized outreach campaigns.', 'An OpenClaw agent monitors alumni news and career updates, identify engagement opportunities (anniversaries, promotions, relocations), generate personalized messages, schedule outreach, and track responses in CRM. OpenClaw monitors alumni activity and triggers personalized outreach campaigns.', 'Education', 'Marketing', ARRAY['OpenClaw', 'CRM', 'Email', 'LinkedIn'], '8-12 hrs/week', 'Simple', 'users', 'a'),

-- Government
('FOIA Request Processing', 'An OpenClaw agent streamlines Freedom of Information Act request intake and fulfillment.', 'An OpenClaw agent parses request emails, extract required information and date ranges, search document repositories, redact sensitive information, generate response packages, and track compliance deadlines. OpenClaw handles FOIA request processing and document preparation end-to-end.', 'Government', 'Operations', ARRAY['OpenClaw', 'Email', 'Document Management', 'Database'], '10-15 hrs/week', 'Advanced', 'document', 'c'),

('Citizen Service Request Routing', 'Automatically categorize and route 311-style service requests to departments.', 'An OpenClaw agent classifies incoming requests by type (pothole, noise complaint, permit), extract location and urgency, assign to appropriate department queues, send acknowledgment to citizen, and track resolution SLAs. OpenClaw routes service requests and tracks resolution using CRM and GIS integrations.', 'Government', 'Operations', ARRAY['OpenClaw', 'CRM', 'Email', 'GIS System'], '12-18 hrs/week', 'Moderate', 'ticket', 'b'),

('Grant Application Scoring', 'An OpenClaw agent pre-screens grant applications against eligibility criteria with scoring.', 'An OpenClaw agent parses application forms, check eligibility requirements, score applications against evaluation criteria, generate reviewer summaries with key strengths/weaknesses, and rank for review committee. OpenClaw pre-screens applications and generates reviewer summaries automatically.', 'Government', 'Finance', ARRAY['OpenClaw', 'Forms Platform', 'Database', 'Email'], '8-12 hrs/week', 'Advanced', 'star', 'a'),

-- Cross-industry / General
('Meeting Notes to Action Items', 'An OpenClaw agent extracts action items from meeting transcripts and create tasks automatically.', 'An OpenClaw agent transcribes meetings, identify action items with owners and due dates, create tickets in project management tools, send summary emails to participants, and set follow-up reminders. OpenClaw extracts action items from meetings and creates tasks across project management tools.', 'Technology', 'Operations', ARRAY['OpenClaw', 'Zoom', 'Slack', 'Jira', 'Email'], '6-10 hrs/week', 'Moderate', 'clipboard', 'a'),

('Invoice Processing Automation', 'An OpenClaw agent extracts data from invoices, match to purchase orders, and route for approval.', 'An OpenClaw agent uses OCR to invoice PDFs, extract vendor, amount, line items, match against POs, flag discrepancies, route to appropriate approvers based on amount and department, and update accounting system upon approval. OpenClaw processes invoices and routes them for approval using OCR and accounting integrations.', 'Financial Services', 'Finance', ARRAY['OpenClaw', 'Email', 'Accounting Software', 'Slack'], '10-15 hrs/week', 'Moderate', 'document', 'c'),

('Employee Onboarding Checklist Automation', 'An OpenClaw agent coordinates cross-functional onboarding tasks with automated reminders.', 'An OpenClaw agent triggers onboarding workflows on hire date, assign tasks to IT, HR, and managers, send reminders for incomplete items, track completion progress, and generate day-1 welcome packet for new hire. OpenClaw coordinates onboarding tasks across IT, HR, and management systems.', 'Technology', 'HR', ARRAY['OpenClaw', 'HRIS', 'Slack', 'Email', 'Jira'], '5-8 hrs/week', 'Simple', 'users', 'b'),

-- Real Estate
('Property Listing Automation', 'An OpenClaw agent generates property listings from inspection reports and photos with market-optimized descriptions.', 'An OpenClaw agent processes property details, inspection reports, and photos, generate compelling listing descriptions optimized for SEO and market trends, post to multiple listing services, and sync with CRM. OpenClaw automates the entire listing workflow from data collection to publishing.', 'Real Estate', 'Operations', ARRAY['OpenClaw', 'MLS', 'CRM', 'Email', 'Slack'], '8-12 hrs/week', 'Moderate', 'document', 'a'),

('Tenant Screening Workflow', 'An OpenClaw agent automates background checks, credit reports, and reference verification for rental applications.', 'An OpenClaw agent collects tenant applications, runs background and credit checks, verifies employment and references, calculates risk scores, and generates approval recommendations with supporting documentation. OpenClaw orchestrates the entire screening process across multiple data sources.', 'Real Estate', 'Operations', ARRAY['OpenClaw', 'Screening Services', 'Database', 'Email'], '10-15 hrs/week', 'Advanced', 'shield', 'c'),

('Property Maintenance Request Routing', 'An OpenClaw agent triages maintenance requests and dispatches them to appropriate vendors with SLA tracking.', 'An OpenClaw agent receives maintenance requests from tenants, categorize by urgency and type, assign to qualified vendors based on availability and specialization, track SLAs, send status updates to tenants, and log completion for property records. OpenClaw manages the full maintenance workflow from request to resolution.', 'Real Estate', 'Operations', ARRAY['OpenClaw', 'Property Management System', 'Slack', 'SMS'], '12-18 hrs/week', 'Moderate', 'wrench', 'b'),

-- Insurance
('Claims Intake and Classification', 'An OpenClaw agent processes insurance claims from multiple channels and automatically routes based on claim type and severity.', 'An OpenClaw agent ingests claims from email, web forms, and mobile apps, extract key information, classify by claim type and estimated severity, check for fraud indicators, assign to appropriate adjusters, and send acknowledgment to claimants. OpenClaw streamlines claims intake across all channels.', 'Insurance', 'Operations', ARRAY['OpenClaw', 'Claims System', 'Email', 'Database'], '15-20 hrs/week', 'Advanced', 'clipboard', 'a'),

('Underwriting Document Analysis', 'An OpenClaw agent reviews underwriting documents and extracts risk factors for policy approval.', 'An OpenClaw agent analyzes application documents, medical records, and financial statements, extract risk factors and key data points, calculate preliminary risk scores, highlight exceptions requiring underwriter review, and generate underwriting summaries. OpenClaw accelerates document review and risk assessment.', 'Insurance', 'Operations', ARRAY['OpenClaw', 'Document Management', 'Underwriting System', 'Database'], '12-18 hrs/week', 'Advanced', 'chart', 'c'),

('Policy Renewal Reminder Automation', 'An OpenClaw agent sends personalized renewal reminders with updated quotes and upsell recommendations.', 'An OpenClaw agent monitors policy expiration dates, generate renewal quotes with market-adjusted rates, identify upsell opportunities based on customer profile changes, send personalized reminders via email and SMS, track responses, and update CRM. OpenClaw manages the full renewal cycle.', 'Insurance', 'Sales', ARRAY['OpenClaw', 'Policy System', 'CRM', 'Email', 'SMS'], '8-12 hrs/week', 'Moderate', 'calendar', 'b'),

-- Consulting
('Proposal Generation from Discovery Notes', 'An OpenClaw agent transforms discovery meeting notes into structured proposals with SOW and pricing.', 'An OpenClaw agent extracts requirements from meeting transcripts and notes, match to service catalog and pricing models, generate customized proposals with scope of work, milestones, and deliverables, apply templates and branding, and route for partner review. OpenClaw accelerates proposal creation from discovery to delivery.', 'Consulting', 'Sales', ARRAY['OpenClaw', 'Meeting Tools', 'Proposal Software', 'CRM'], '10-15 hrs/week', 'Advanced', 'document', 'a'),

('Client Time Tracking and Billing', 'An OpenClaw agent aggregates timesheet data and generates accurate client invoices with project breakdowns.', 'An OpenClaw agent collects time entries from consultants, validate against project budgets, calculate billable amounts by rate card, generate itemized invoices with project milestones, send for client approval, and sync with accounting system. OpenClaw ensures accurate and timely billing.', 'Consulting', 'Finance', ARRAY['OpenClaw', 'Time Tracking', 'Accounting Software', 'Email'], '12-18 hrs/week', 'Moderate', 'document', 'c'),

('Knowledge Base Article Generation', 'An OpenClaw agent converts project deliverables into reusable knowledge base articles and case studies.', 'An OpenClaw agent identifies completed projects, extract methodologies and outcomes, generate structured KB articles with best practices, anonymize client details, tag by industry and service line, and publish to internal knowledge management system. OpenClaw builds institutional knowledge from project work.', 'Consulting', 'Operations', ARRAY['OpenClaw', 'Project Management', 'Confluence', 'Notion'], '6-10 hrs/week', 'Moderate', 'document', 'b'),

-- Media & Entertainment
('Content Publishing Scheduler', 'An OpenClaw agent schedules and publishes content across platforms with optimal timing and cross-posting.', 'An OpenClaw agent analyzes audience engagement patterns, determine optimal publish times by platform, schedule posts with platform-specific formatting, cross-post to multiple channels, track performance metrics, and adjust scheduling based on results. OpenClaw manages multi-platform publishing.', 'Media', 'Marketing', ARRAY['OpenClaw', 'Social Media Tools', 'CMS', 'Analytics'], '8-12 hrs/week', 'Moderate', 'calendar', 'a'),

('Ad Campaign Performance Reporting', 'An OpenClaw agent aggregates campaign metrics and generates performance reports with recommendations.', 'An OpenClaw agent pulls data from ad platforms, calculate ROI and engagement metrics, identify top and bottom performers, generate visualizations and executive summaries, flag budget anomalies, and distribute weekly reports to stakeholders. OpenClaw delivers comprehensive campaign insights.', 'Media', 'Marketing', ARRAY['OpenClaw', 'Ad Platforms', 'Analytics', 'Slack', 'Email'], '10-15 hrs/week', 'Advanced', 'chart', 'c'),

('Content Rights Management', 'An OpenClaw agent tracks content licensing, usage rights, and renewal deadlines with automated alerts.', 'An OpenClaw agent monitors content libraries, track licensing agreements and expiration dates, flag usage violations, send renewal reminders, generate rights reports by project, and maintain audit trail for compliance. OpenClaw ensures content usage stays compliant.', 'Media', 'Legal', ARRAY['OpenClaw', 'DAM System', 'Database', 'Email'], '6-10 hrs/week', 'Moderate', 'shield', 'b'),

-- Logistics & Transportation
('Shipment Tracking and Status Updates', 'An OpenClaw agent monitors shipments across carriers and sends proactive status updates to customers.', 'An OpenClaw agent tracks shipments via carrier APIs, detect delays or exceptions, send automated notifications to customers, provide estimated delivery updates, escalate issues to logistics team, and maintain delivery records. OpenClaw provides end-to-end shipment visibility.', 'Logistics', 'Operations', ARRAY['OpenClaw', 'Carrier APIs', 'Email', 'SMS', 'CRM'], '12-18 hrs/week', 'Advanced', 'link', 'a'),

('Route Optimization for Deliveries', 'An OpenClaw agent calculates optimal delivery routes based on traffic, priority, and vehicle capacity.', 'An OpenClaw agent analyzes delivery addresses, real-time traffic data, package priorities, and vehicle constraints, generate optimized routes minimizing fuel and time, send route assignments to drivers, adjust dynamically for new orders or delays, and track route efficiency. OpenClaw optimizes daily delivery operations.', 'Logistics', 'Operations', ARRAY['OpenClaw', 'Routing Software', 'Maps API', 'Mobile Apps'], '15-20 hrs/week', 'Advanced', 'chart', 'c'),

('Warehouse Inventory Alerts', 'An OpenClaw agent monitors stock levels and triggers reorder workflows based on demand forecasts.', 'An OpenClaw agent tracks inventory levels in real-time, predict stockouts using demand patterns, generate reorder recommendations, create purchase orders, notify procurement team, and update inventory management system. OpenClaw prevents stockouts and optimizes inventory levels.', 'Logistics', 'Operations', ARRAY['OpenClaw', 'Inventory System', 'ERP', 'Slack'], '8-12 hrs/week', 'Moderate', 'alert', 'b'),

-- Hospitality
('Guest Booking Confirmation Workflow', 'An OpenClaw agent sends personalized booking confirmations with pre-arrival information and upsell offers.', 'An OpenClaw agent processes new bookings, send confirmation emails with property details and check-in instructions, identify upsell opportunities, send pre-arrival surveys, sync with property management system, and create guest profiles. OpenClaw enhances guest experience from booking to arrival.', 'Hospitality', 'Operations', ARRAY['OpenClaw', 'PMS', 'Email', 'CRM'], '10-15 hrs/week', 'Simple', 'calendar', 'a'),

('Guest Feedback Collection and Analysis', 'An OpenClaw agent automates post-stay surveys and analyzes feedback to identify improvement areas.', 'An OpenClaw agent sends post-checkout surveys, collect responses, perform sentiment analysis, categorize feedback by department and issue type, flag negative reviews for immediate response, generate trend reports, and route actionable insights to operations teams. OpenClaw turns guest feedback into operational improvements.', 'Hospitality', 'Operations', ARRAY['OpenClaw', 'Survey Tools', 'Review Sites', 'Slack'], '8-12 hrs/week', 'Moderate', 'star', 'c'),

('Housekeeping Task Assignment', 'An OpenClaw agent optimizes housekeeping schedules based on checkouts, VIP guests, and room priorities.', 'An OpenClaw agent monitors checkout schedule and new arrivals, prioritize rooms by check-in time and guest status, assign tasks to housekeeping staff based on availability and workload, send mobile notifications, track completion, and update room status in PMS. OpenClaw streamlines housekeeping operations.', 'Hospitality', 'Operations', ARRAY['OpenClaw', 'PMS', 'Mobile Apps', 'Slack'], '12-18 hrs/week', 'Moderate', 'clipboard', 'b'),

-- Agriculture
('Crop Monitoring and Alert System', 'An OpenClaw agent analyzes sensor data from fields and alerts farmers to irrigation, pest, or disease issues.', 'An OpenClaw agent monitors IoT sensors for soil moisture, temperature, and crop health, detect anomalies, predict irrigation needs, identify pest or disease indicators, send alerts to farmers with recommended actions, and log interventions for compliance records. OpenClaw enables precision agriculture.', 'Agriculture', 'Operations', ARRAY['OpenClaw', 'IoT Platform', 'SMS', 'Database'], '10-15 hrs/week', 'Advanced', 'alert', 'a'),

('Supply Chain Logistics for Produce', 'An OpenClaw agent coordinates harvest schedules, transportation, and delivery to minimize spoilage.', 'An OpenClaw agent monitors harvest readiness, schedule transportation based on weather and buyer demand, optimize routes to minimize transit time, track cold chain compliance, alert to delays, and generate delivery confirmations. OpenClaw reduces spoilage through optimized logistics.', 'Agriculture', 'Operations', ARRAY['OpenClaw', 'Logistics Software', 'IoT', 'Email'], '12-18 hrs/week', 'Advanced', 'link', 'c'),

('Farm Compliance Reporting', 'An OpenClaw agent compiles regulatory compliance reports for organic certification and food safety.', 'An OpenClaw agent collects farm activity logs, pesticide usage records, and soil test results, verify compliance with organic and food safety standards, generate formatted reports, submit to regulatory bodies, and maintain audit trails. OpenClaw simplifies compliance documentation.', 'Agriculture', 'Operations', ARRAY['OpenClaw', 'Farm Management Software', 'Database', 'Email'], '6-10 hrs/week', 'Moderate', 'clipboard', 'b'),

-- Energy & Utilities
('Energy Usage Forecasting', 'An OpenClaw agent predicts energy demand based on weather, historical patterns, and planned outages.', 'An OpenClaw agent analyzes historical consumption data, weather forecasts, and scheduled maintenance, generate demand predictions, identify peak load periods, recommend load balancing strategies, and distribute forecasts to operations teams. OpenClaw improves grid management and cost efficiency.', 'Energy', 'Operations', ARRAY['OpenClaw', 'SCADA', 'Weather API', 'Database'], '10-15 hrs/week', 'Advanced', 'chart', 'a'),

('Utility Compliance and Safety Reporting', 'An OpenClaw agent automates regulatory compliance reporting for safety incidents and environmental impact.', 'An OpenClaw agent collects incident reports, emissions data, and safety inspections, verify compliance with regulations, generate formatted reports, submit to regulatory agencies, track deadlines, and maintain audit documentation. OpenClaw ensures timely and accurate compliance reporting.', 'Energy', 'Operations', ARRAY['OpenClaw', 'Database', 'Document Management', 'Email'], '8-12 hrs/week', 'Advanced', 'clipboard', 'c'),

('Outage Detection and Customer Notification', 'An OpenClaw agent detects power outages and sends automated notifications to affected customers with ETAs.', 'An OpenClaw agent monitors grid sensors, detect outages, identify affected service areas, estimate restoration times, send notifications to customers via SMS and email, update outage maps, and log restoration progress. OpenClaw improves customer communication during outages.', 'Energy', 'Customer Support', ARRAY['OpenClaw', 'SCADA', 'CRM', 'SMS', 'Email'], '12-18 hrs/week', 'Moderate', 'alert', 'b'),

-- Telecommunications
('Network Issue Ticket Routing', 'An OpenClaw agent classifies network tickets and routes them to specialized engineering teams.', 'An OpenClaw agent parses incoming tickets, extract network location and issue type, classify by severity and affected services, assign to appropriate engineering teams, attach diagnostic data, and track SLAs. OpenClaw accelerates network issue resolution.', 'Telecom', 'Engineering', ARRAY['OpenClaw', 'Ticketing System', 'Network Monitoring', 'Slack'], '15-20 hrs/week', 'Advanced', 'ticket', 'a'),

('Customer Account Provisioning', 'An OpenClaw agent automates new customer setups including service activation and billing configuration.', 'An OpenClaw agent processes new service orders, provision network equipment, configure billing systems, activate customer accounts, send welcome emails with service details, and notify field techs for physical installations. OpenClaw streamlines customer onboarding.', 'Telecom', 'Operations', ARRAY['OpenClaw', 'BSS/OSS', 'CRM', 'Email'], '10-15 hrs/week', 'Moderate', 'rocket', 'c'),

('Network Performance Monitoring', 'An OpenClaw agent analyzes network telemetry and alerts engineers to performance degradation.', 'An OpenClaw agent monitors network KPIs (latency, packet loss, bandwidth), detect anomalies and performance degradation, predict potential failures, generate alerts with diagnostic context, route to on-call engineers, and log incidents for trend analysis. OpenClaw enables proactive network management.', 'Telecom', 'Engineering', ARRAY['OpenClaw', 'Network Monitoring', 'PagerDuty', 'Slack'], '12-18 hrs/week', 'Advanced', 'chart', 'b'),

-- Nonprofit
('Donor Management and Acknowledgment', 'An OpenClaw agent processes donations and sends personalized thank-you messages with tax receipts.', 'An OpenClaw agent records donations, generate tax receipts, send personalized acknowledgment emails, update donor CRM, flag major gifts for personal outreach, track giving patterns, and generate donor reports for development team. OpenClaw improves donor relationships and compliance.', 'Nonprofit', 'Finance', ARRAY['OpenClaw', 'CRM', 'Accounting Software', 'Email'], '8-12 hrs/week', 'Moderate', 'star', 'a'),

('Grant Application and Reporting', 'An OpenClaw agent tracks grant deadlines, compiles reporting data, and generates submission-ready reports.', 'An OpenClaw agent monitors grant deadlines, collect program metrics and outcomes data, generate formatted reports with required documentation, route for approval, submit to funders, and maintain grant compliance records. OpenClaw ensures timely and accurate grant reporting.', 'Nonprofit', 'Finance', ARRAY['OpenClaw', 'Database', 'Document Management', 'Email'], '12-18 hrs/week', 'Advanced', 'document', 'c'),

('Volunteer Scheduling and Communication', 'An OpenClaw agent matches volunteers to opportunities and sends shift reminders and updates.', 'An OpenClaw agent analyzes volunteer skills and availability, match to program needs, send shift invitations, track confirmations, send reminders, collect post-shift feedback, and update volunteer hours in CRM. OpenClaw optimizes volunteer engagement and retention.', 'Nonprofit', 'Operations', ARRAY['OpenClaw', 'Volunteer Management', 'Email', 'SMS'], '6-10 hrs/week', 'Simple', 'users', 'b');
